[package]
name = "mono_slam"
version = "0.1.0"
authors = ["Sebastian <sebasgarcep@gmail.com>"]
build = "build.rs"

[dependencies]
image = "0.19.0"
lazy_static = "1.1.0"
ndarray = "0.12.0"
ndarray-linalg = "0.10.0"
openblas-src = "0.6.0"
piston_window = "0.80.0"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"
uvc = "0.1.0"
